title: NGUYEN THI CHAU NGOC
#logo: /assets/20120146_Nguy%E1%BB%85n%20Th%E1%BB%8B%20Ch%C3%A2u%20Ng%E1%BB%8Dc.jpg
#description: Data Analyst and Data Scientist
#show_downloads: true
theme: jekyll-theme-cayman
